sudo: required
services:
  - docker

before_install:
  - docker build -t sunnynehar56/cicd-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunnynehar56/cicd-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "cicd-react"
  env: "CicdReact-env" 
  bucket_name: elasticbeanstalk-eu-west-2-187498025781
  bucket_path: "cicd-react"
  on:
    branch: master
  access_key_id: "$access_key"
  secret_access_key:
    secure: "$secret_key"