sudo: required
services:
  - docker

before_install:
  - docker build -t sunnynehar56/cicd-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunnynehar56/cicd-react npm run test -- --coverage